services:
  node:
    image: "node:20.12.2-alpine"
    user: "node"
    working_dir: /home/node/app
    env_file: ".env"
    volumes:
      - ./:/home/node/app
    ports:
      - "8080:8080"
    command: npm start
  db:
    image: "postgres:15.7-alpine"
    environment:
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
